server:
  port: 8020
#应用名称（nacos会将该名称当作服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: lucy
        password: lucy
#        namespace可以表示生产还是测试环境
        namespace: prod
        group: "group1"
        cache-refresh-interval: 1000
#logging:
#  level:
#    root: debug
feign:
  client:
    config:
      default:
        loggerLevel: full
        read-timeout: 1000
        connect-timeout: 1000