server:
  port: 8021
#应用名称（nacos会将该名称当作服务名称）
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        #        namespace可以表示生产还是测试环境
        namespace: prod
        group: group1
#        ephemeral如果是false表示是永久实例
        ephemeral: true
#        权重越高分配的流量越大
        weight: 2
#        用于做扩展
        metadata:
          version: 1
    alibaba:
      seata:
        tx-service-group: guangzhou
seata:
  registry:
    type: nacos
    nacos:
      username: nacos
      password: nacos
      namespace:
      group: SEATA_GROUP
      application: seata-server
      server-addr: localhost:8848
      cluster: default
  config:
    nacos:
      username: nacos
      password: nacos
      namespace:
      group: SEATA_GROUP
      server-addr: localhost:8848
    type: nacos
